### ISSUE TITLE
Double check: "400m2 radius" is radius not area?

### ISSUE THREAD

**Issue by hrlai** [wengngai/NSSF_IBMs#8]
so it is actually 400m? 

Just checking

**Comment by wengngai** [comment]
Apologies. This is simply poor english on my part. Radius is correct, because we're talking about distance (spDist) from the focal individual. However, we have to make sure that the total area in which competition is measured in the IBM (the circle around the focal individual) is equal to the total area in which competition was measured in the field (20x20m plot). Since 20*20=pi*r^2, then r = sqrt(400/pi). That's what "400m2 radius" meant, though it's quite bad english haha..
*Note that in intra/inter.dist.calc, r = sqrt(1600/pi) instead, because this measure was done within the expanded 40x40m plot extent.
I checked through and this should be correct in CAE/HAE.calc, intra/inter.calc, and intra/inter.dist.calc
